package cat.mrtxema.crispetes.model;

public enum CrewJob {
    SCREENPLAY("Screenplay"),
    AUTHOR("Author"),
    NOVEL("Novel"),
    CHARACTERS("Characters"),
    THEATRE_PLAY("Theatre Play"),
    ADAPTATION("Adaptation"),
    DIALOGUE("Dialogue"),
    WRITER("Writer"),
    STORYBOARD("Storyboard"),
    ORIGINAL_STORY("Original Story"),
    SCENARIO_WRITER("Scenario Writer"),
    SCREENSTORY("Screenstory"),
    MUSICAL("Musical"),
    IDEA("Idea"),
    STORY("Story"),
    CREATIVE_PRODUCER("Creative Producer"),
    TELEPLAY("Teleplay"),
    OPERA("Opera"),
    COWRITER("Co-Writer"),
    BOOK("Book"),
    COMIC_BOOK("Comic Book"),
    SHORT_STORY("Short Story"),
    SERIES_COMPOSITION("Series Composition"),
    SCRIPT_EDITOR("Script Editor"),
    DIRECTOR("Director"),
    SCRIPT_SUPERVISOR("Script Supervisor"),
    LAYOUT("Layout"),
    SCRIPT_COORDINATOR("Script Coordinator"),
    SPECIAL_GUEST_DIRECTOR("Special Guest Director"),
    ASSISTANT_DIRECTOR("Assistant Director"),
    ACTOR("Actor"),
    STUNT_DOUBLE("Stunt Double"),
    VOICE("Voice"),
    CAMEO("Cameo"),
    SPECIAL_GUEST("Special Guest"),
    DIRECTOR_OF_PHOTOGRAPHY("Director of Photography"),
    UNDERWATER_CAMERA("Underwater Camera"),
    CAMERA_OPERATOR("Camera Operator"),
    STILL_PHOTOGRAPHER("Still Photographer"),
    CAMERA_DEPARTMENT_MANAGER("Camera Department Manager"),
    CAMERA_SUPERVISOR("Camera Supervisor"),
    CAMERA_TECHNICIAN("Camera Technician"),
    GRIP("Grip"),
    STEADICAM_OPERATOR("Steadicam Operator"),
    ADDITIONAL_CAMERA("Additional Camera"),
    CAMERA_INTERN("Camera Intern"),
    ADDITIONAL_PHOTOGRAPHY("Additional Photography"),
    HELICOPTER_CAMERA("Helicopter Camera"),
    FIRST_ASSISTANT_CAMERA("First Assistant Camera"),
    EDITOR("Editor"),
    SUPERVISING_FILM_EDITOR("Supervising Film Editor"),
    ADDITIONAL_EDITING("Additional Editing"),
    EDITORIAL_MANAGER("Editorial Manager"),
    FIRST_ASSISTANT_EDITOR("First Assistant Editor"),
    ADDITIONAL_EDITORIAL_ASSISTANT("Additional Editorial Assistant"),
    EDITORIAL_COORDINATOR("Editorial Coordinator"),
    EDITORIAL_PRODUCTION_ASSISTANT("Editorial Production Assistant"),
    EDITORIAL_SERVICES("Editorial Services"),
    DIALOGUE_EDITOR("Dialogue Editor"),
    ARCHIVAL_FOOTAGE_COORDINATOR("Archival Footage Coordinator"),
    ARCHIVAL_FOOTAGE_RESEARCH("Archival Footage Research"),
    COLOR_TIMER("Color Timer"),
    DIGITAL_INTERMEDIATE("Digital Intermediate"),
    ASSISTANT_EDITOR("Assistant Editor"),
    PRODUCTION_DESIGN("Production Design"),
    ART_DIRECTION("Art Direction"),
    SET_DECORATION("Set Decoration"),
    SET_DESIGNER("Set Designer"),
    CONCEPTUAL_DESIGN("Conceptual Design"),
    INTERIOR_DESIGNER("Interior Designer"),
    SETTINGS("Settings"),
    ASSISTANT_ART_DIRECTOR("Assistant Art Director"),
    ART_DEPARTMENT_COORDINATOR("Art Department Coordinator"),
    ART_DEPARTMENT_MANAGER("Art Department Manager"),
    SCULPTOR("Sculptor"),
    ART_DEPARTMENT_ASSISTANT("Art Department Assistant"),
    BACKGROUND_DESIGNER("Background Designer"),
    COART_DIRECTOR("Co-Art Director"),
    SET_DECORATION_BUYER("Set Decoration Buyer"),
    PRODUCTION_ILLUSTRATOR("Production Illustrator"),
    STANDBY_PAINTER("Standby Painter"),
    LOCATION_SCOUT("Location Scout"),
    SUPERVISING_ART_DIRECTOR("Supervising Art Director"),
    LEADMAN("Leadman"),
    GREENSMAN("Greensman"),
    GUN_WRANGLER("Gun Wrangler"),
    CONSTRUCTION_COORDINATOR("Construction Coordinator"),
    CONSTRUCTION_FOREMAN("Construction Foreman"),
    LEAD_PAINTER("Lead Painter"),
    SIGN_PAINTER("Sign Painter"),
    PAINTER("Painter"),
    COSTUME_DESIGN("Costume Design"),
    MAKEUP_ARTIST("Makeup Artist"),
    HAIRSTYLIST("Hairstylist"),
    SET_DRESSING_ARTIST("Set Dressing Artist"),
    SET_DRESSING_SUPERVISOR("Set Dressing Supervisor"),
    SET_DRESSING_MANAGER("Set Dressing Manager"),
    SET_DRESSING_PRODUCTION_ASSISTANT("Set Dressing Production Assistant"),
    FACIAL_SETUP_ARTIST("Facial Setup Artist"),
    HAIR_SETUP("Hair Setup"),
    COSTUME_SUPERVISOR("Costume Supervisor"),
    SET_COSTUMER("Set Costumer"),
    MAKEUP_DEPARTMENT_HEAD("Makeup Department Head"),
    WIGMAKER("Wigmaker"),
    SHOE_DESIGN("Shoe Design"),
    COCOSTUME_DESIGNER("Co-Costume Designer"),
    HAIR_DEPARTMENT_HEAD("Hair Department Head"),
    HAIR_DESIGNER("Hair Designer"),
    MAKEUP_DESIGNER("Makeup Designer"),
    ASSISTANT_COSTUME_DESIGNER("Assistant Costume Designer"),
    PROSTHETIC_SUPERVISOR("Prosthetic Supervisor"),
    SEAMSTRESS("Seamstress"),
    KEY_HAIR_STYLIST("Key Hair Stylist"),
    PRODUCER("Producer"),
    EXECUTIVE_PRODUCER("Executive Producer"),
    CASTING("Casting"),
    PRODUCTION_MANAGER("Production Manager"),
    UNIT_PRODUCTION_MANAGER("Unit Production Manager"),
    LINE_PRODUCER("Line Producer"),
    LOCATION_MANAGER("Location Manager"),
    PRODUCTION_SUPERVISOR("Production Supervisor"),
    PRODUCTION_ACCOUNTANT("Production Accountant"),
    PRODUCTION_OFFICE_COORDINATOR("Production Office Coordinator"),
    FINANCE("Finance"),
    EXECUTIVE_CONSULTANT("Executive Consultant"),
    CHARACTER_TECHNICAL_SUPERVISOR("Character Technical Supervisor"),
    DEVELOPMENT_MANAGER("Development Manager"),
    ADMINISTRATION("Administration"),
    EXECUTIVE_IN_CHARGE_OF_POST_PRODUCTION("Executive In Charge Of Post Production"),
    PRODUCTION_DIRECTOR("Production Director"),
    EXECUTIVE_IN_CHARGE_OF_PRODUCTION("Executive In Charge Of Production"),
    PUBLICIST("Publicist"),
    ASSOCIATE_PRODUCER("Associate Producer"),
    COPRODUCER("Co-Producer"),
    COEXECUTIVE_PRODUCER("Co-Executive Producer"),
    CASTING_ASSOCIATE("Casting Associate"),
    RESEARCHER("Researcher"),
    PRODUCTION_COORDINATOR("Production Coordinator"),
    CONSULTING_PRODUCER("Consulting Producer"),
    SUPERVISING_PRODUCER("Supervising Producer"),
    SENIOR_EXECUTIVE_CONSULTANT("Senior Executive Consultant"),
    UNIT_MANAGER("Unit Manager"),
    ORIGINAL_MUSIC_COMPOSER("Original Music Composer"),
    SOUND_DESIGNER("Sound Designer"),
    SOUND_EDITOR("Sound Editor"),
    SOUND_DIRECTOR("Sound Director"),
    SOUND_MIXER("Sound Mixer"),
    MUSIC_EDITOR("Music Editor"),
    SOUND_EFFECTS_EDITOR("Sound Effects Editor"),
    PRODUCTION_SOUND_MIXER("Production Sound Mixer"),
    ADDITIONAL_SOUNDTRACK("Additional Soundtrack"),
    SUPERVISING_SOUND_EDITOR("Supervising Sound Editor"),
    SUPERVISING_SOUND_EFFECTS_EDITOR("Supervising Sound Effects Editor"),
    SOUND_RERECORDING_MIXER("Sound Re-Recording Mixer"),
    RECORDING_SUPERVISION("Recording Supervision"),
    BOOM_OPERATOR("Boom Operator"),
    SOUND_MONTAGE_ASSOCIATE("Sound Montage Associate"),
    SONGS("Songs"),
    MUSIC("Music"),
    ADR_DUBBING("ADR & Dubbing"),
    SOUND_ENGINEER("Sound Engineer"),
    FOLEY("Foley"),
    ADDITIONAL_MUSIC_SUPERVISOR("Additional Music Supervisor"),
    FIRST_ASSISTANT_SOUND_EDITOR("First Assistant Sound Editor"),
    SCORING_MIXER("Scoring Mixer"),
    DOLBY_CONSULTANT("Dolby Consultant"),
    MUSIC_DIRECTOR("Music Director"),
    ORCHESTRATOR("Orchestrator"),
    VOCAL_COACH("Vocal Coach"),
    MUSIC_SUPERVISOR("Music Supervisor"),
    SOUND("Sound"),
    ANIMATION("Animation"),
    VISUAL_EFFECTS("Visual Effects"),
    CHIEF_TECHNICIAN_STOPMOTION_EXPERT("Chief Technician / Stop-Motion Expert"),
    CREATURE_DESIGN("Creature Design"),
    SHADING("Shading"),
    MODELING("Modeling"),
    CG_PAINTER("CG Painter"),
    VISUAL_DEVELOPMENT("Visual Development"),
    ANIMATION_MANAGER("Animation Manager"),
    ANIMATION_DIRECTOR("Animation Director"),
    FIX_ANIMATOR("Fix Animator"),
    ANIMATION_DEPARTMENT_COORDINATOR("Animation Department Coordinator"),
    ANIMATION_FIX_COORDINATOR("Animation Fix Coordinator"),
    ANIMATION_PRODUCTION_ASSISTANT("Animation Production Assistant"),
    VISUAL_EFFECTS_SUPERVISOR("Visual Effects Supervisor"),
    MECHANICAL_CREATURE_DESIGNER("Mechanical & Creature Designer"),
    BATTLE_MOTION_COORDINATOR("Battle Motion Coordinator"),
    ANIMATION_SUPERVISOR("Animation Supervisor"),
    VFX_SUPERVISOR("VFX Supervisor"),
    CLOTH_SETUP("Cloth Setup"),
    VFX_ARTIST("VFX Artist"),
    CG_ENGINEER("CG Engineer"),
    FRAME24_PLAYBACK("24 Frame Playback"),
    IMAGING_SCIENCE("Imaging Science"),
    IO_SUPERVISOR("I/O Supervisor"),
    VISUAL_EFFECTS_PRODUCER("Visual Effects Producer"),
    VFX_PRODUCTION_COORDINATOR("VFX Production Coordinator"),
    IO_MANAGER("I/O Manager"),
    ADDITIONAL_EFFECTS_DEVELOPMENT("Additional Effects Development"),
    COLOR_DESIGNER("Color Designer"),
    SIMULATION_EFFECTS_PRODUCTION_ASSISTANT("Simulation & Effects Production Assistant"),
    SIMULATION_EFFECTS_ARTIST("Simulation & Effects Artist"),
    PYROTECHNIC_SUPERVISOR("Pyrotechnic Supervisor"),
    SPECIAL_EFFECTS_SUPERVISOR("Special Effects Supervisor"),
    SUPERVISOR_3D("3D Supervisor"),
    DIRECTOR_3D("3D Director"),
    DIGITAL_COMPOSITORS("Digital Compositors"),
    VISUAL_EFFECTS_COORDINATOR("Visual Effects Coordinator"),
    VFX_EDITOR("VFX Editor"),
    SPECIAL_EFFECTS("Special Effects"),
    POST_PRODUCTION_SUPERVISOR("Post Production Supervisor"),
    SECOND_UNIT("Second Unit"),
    CHOREOGRAPHER("Choreographer"),
    STUNTS("Stunts"),
    SOUND_RECORDIST("Sound Recordist"),
    STUNT_COORDINATOR("Stunt Coordinator"),
    SPECIAL_EFFECTS_COORDINATOR("Special Effects Coordinator"),
    SUPERVISING_TECHNICAL_DIRECTOR("Supervising Technical Director"),
    SUPERVISING_ANIMATOR("Supervising Animator"),
    PRODUCTION_ARTIST("Production Artist"),
    SEQUENCE_LEADS("Sequence Leads"),
    SECOND_FILM_EDITOR("Second Film Editor"),
    TEMP_MUSIC_EDITOR("Temp Music Editor"),
    TEMP_SOUND_EDITOR("Temp Sound Editor"),
    SEQUENCE_SUPERVISOR("Sequence Supervisor"),
    SOFTWARE_TEAM_LEAD("Software Team Lead"),
    SOFTWARE_ENGINEER("Software Engineer"),
    DOCUMENTATION_SUPPORT("Documentation & Support"),
    MACHINIST("Machinist"),
    PHOTOSCIENCE_MANAGER("Photoscience Manager"),
    DEPARTMENT_ADMINISTRATOR("Department Administrator"),
    SCHEDULE_COORDINATOR("Schedule Coordinator"),
    SUPERVISOR_OF_PRODUCTION_RESOURCES("Supervisor of Production Resources"),
    PRODUCTION_OFFICE_ASSISTANT("Production Office Assistant"),
    INFORMATION_SYSTEMS_MANAGER("Information Systems Manager"),
    SYSTEMS_ADMINISTRATORS_SUPPORT("Systems Administrators & Support"),
    PROJECTION("Projection"),
    POST_PRODUCTION_ASSISTANT("Post Production Assistant"),
    SOUND_DESIGN_ASSISTANT("Sound Design Assistant"),
    MIX_TECHNICIAN("Mix Technician"),
    MOTION_ACTOR("Motion Actor"),
    SETS_PROPS_SUPERVISOR("Sets & Props Supervisor"),
    COMPOSITORS("Compositors"),
    TATTOOIST("Tattooist"),
    SETS_PROPS_ARTIST("Sets & Props Artist"),
    MOTION_CAPTURE_ARTIST("Motion Capture Artist"),
    SEQUENCE_ARTIST("Sequence Artist"),
    MIXING_ENGINEER("Mixing Engineer"),
    SPECIAL_SOUND_EFFECTS("Special Sound Effects"),
    POSTPRODUCTION_MANAGER("Post-Production Manager"),
    DIALECT_COACH("Dialect Coach"),
    PICTURE_CAR_COORDINATOR("Picture Car Coordinator"),
    PROPERTY_MASTER("Property Master"),
    CABLEMAN("Cableman"),
    SET_PRODUCTION_ASSISTANT("Set Production Assistant"),
    VIDEO_ASSIST_OPERATOR("Video Assist Operator"),
    UNIT_PUBLICIST("Unit Publicist"),
    SET_MEDIC("Set Medic"),
    STAND_IN("Stand In"),
    TRANSPORTATION_COORDINATOR("Transportation Coordinator"),
    TRANSPORTATION_CAPTAIN("Transportation Captain"),
    STUNTS_COORDINATOR("Stunts Coordinator"),
    POST_PRODUCTION_CONSULTING("Post Production Consulting"),
    PRODUCTION_INTERN("Production Intern"),
    UTILITY_STUNTS("Utility Stunts"),
    ACTOR_ASSISTANT("Actor's Assistant"),
    SET_PRODUCTION_INTERN("Set Production Intern"),
    PRODUCTION_CONTROLLER("Production Controller"),
    STUDIO_TEACHERS("Studio Teachers"),
    CHEF("Chef"),
    CRAFT_SERVICE("Craft Service"),
    SCENIC_ARTIST("Scenic Artist"),
    PROPMAKER("Propmaker"),
    PROP_MAKER("Prop Maker"),
    TRANSPORTATION_COCAPTAIN("Transportation Co-Captain"),
    DRIVER("Driver"),
    SECURITY("Security"),
    SECOND_UNIT_CINEMATOGRAPHER("Second Unit Cinematographer"),
    LOADER("Loader"),
    MANAGER_OF_OPERATIONS("Manager of Operations"),
    QUALITY_CONTROL_SUPERVISOR("Quality Control Supervisor"),
    LEGAL_SERVICES("Legal Services"),
    PUBLIC_RELATIONS("Public Relations"),
    SCORE_ENGINEER("Score Engineer"),
    TRANSLATOR("Translator"),
    TITLE_GRAPHICS("Title Graphics"),
    TELECINE_COLORIST("Telecine Colorist"),
    ANIMATRONIC_AND_PROSTHETIC_EFFECTS("Animatronic and Prosthetic Effects"),
    MARTIAL_ARTS_CHOREOGRAPHER("Martial Arts Choreographer"),
    CINEMATOGRAPHY("Cinematography"),
    STEADYCAM("Steadycam"),
    EXECUTIVE_VISUAL_EFFECTS_PRODUCER("Executive Visual Effects Producer"),
    VISUAL_EFFECTS_DESIGN_CONSULTANT("Visual Effects Design Consultant"),
    DIGITAL_EFFECTS_SUPERVISOR("Digital Effects Supervisor"),
    DIGITAL_PRODUCER("Digital Producer"),
    CG_SUPERVISOR("CG Supervisor"),
    VISUAL_EFFECTS_ART_DIRECTOR("Visual Effects Art Director"),
    VISUAL_EFFECTS_EDITOR("Visual Effects Editor"),
    EXECUTIVE_IN_CHARGE_OF_FINANCE("Executive in Charge of Finance"),
    ASSOCIATE_CHOREOGRAPHER("Associate Choreographer"),
    MAKEUP_EFFECTS("Makeup Effects"),
    TREATMENT("Treatment"),
    DRAMATURGY("Dramaturgy"),
    LIGHTING_CAMERA("Lighting Camera"),
    TECHNICAL_SUPERVISOR("Technical Supervisor"),
    CGI_SUPERVISOR("CGI Supervisor"),
    CREATIVE_CONSULTANT("Creative Consultant"),
    SCRIPT("Script"),
    EXECUTIVE_MUSIC_PRODUCER("Executive Music Producer"),
    COMMISSIONING_EDITOR("Commissioning Editor"),
    ADDITIONAL_WRITING("Additional Writing"),
    ADDITIONAL_MUSIC("Additional Music"),
    POEM("Poem"),
    THANKS("Thanks"),
    CREATOR("Creator"),
    ADDITIONAL_DIALOGUE("Additional Dialogue"),
    VIDEO_GAME("Video Game"),
    GRAPHIC_NOVEL_ILLUSTRATOR("Graphic Novel Illustrator"),
    SERIES_WRITER("Series Writer"),
    RADIO_PLAY("Radio Play"),
    ARMORER("Armorer"),
    CARPENTER("Carpenter"),
    EDITORIAL_STAFF("Editorial Staff"),
    LIGHTING_TECHNICIAN("Lighting Technician"),
    BEST_BOY_ELECTRIC("Best Boy Electric"),
    GAFFER("Gaffer"),
    RIGGING_GAFFER("Rigging Gaffer"),
    LIGHTING_SUPERVISOR("Lighting Supervisor"),
    LIGHTING_MANAGER("Lighting Manager"),
    DIRECTING_LIGHTING_ARTIST("Directing Lighting Artist"),
    MASTER_LIGHTING_ARTIST("Master Lighting Artist"),
    LIGHTING_ARTIST("Lighting Artist"),
    LIGHTING_COORDINATOR("Lighting Coordinator"),
    LIGHTING_PRODUCTION_ASSISTANT("Lighting Production Assistant"),
    BEST_BOY_ELECTRICIAN("Best Boy Electrician"),
    ELECTRICIAN("Electrician"),
    RIGGING_GRIP("Rigging Grip"),
    OTHER("Other");

    private final String name;

    private CrewJob(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
